# Site settings
author: JA
title: Code Every day
header-img: img/home-bg.png
email: wooke2e@gmail.com
copyright_name: JA
description: > # this means to ignore newlines until "baseurl:"
  Testing code everyday
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  wwkk08

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
